// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/cpu.dart';
import 'api/process.dart';
import 'api/ram.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1642577770;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_system_breakdown',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  bool crateApiCpuCpuAutoAccessorGetAesSupport({required Cpu that});

  Uint64List crateApiCpuCpuAutoAccessorGetCoreSpeeds({required Cpu that});

  Float32List crateApiCpuCpuAutoAccessorGetCoreUsages({required Cpu that});

  String crateApiCpuCpuAutoAccessorGetCpuBrand({required Cpu that});

  BigInt crateApiCpuCpuAutoAccessorGetCpuCores({required Cpu that});

  BigInt crateApiCpuCpuAutoAccessorGetCpuThreads({required Cpu that});

  String crateApiCpuCpuAutoAccessorGetCpuVendor({required Cpu that});

  BigInt crateApiCpuCpuAutoAccessorGetL1Cache({required Cpu that});

  BigInt crateApiCpuCpuAutoAccessorGetL2Cache({required Cpu that});

  BigInt crateApiCpuCpuAutoAccessorGetL3Cache({required Cpu that});

  bool crateApiCpuCpuAutoAccessorGetSha256Support({required Cpu that});

  String crateApiCpuCpuAutoAccessorGetSseFeatures({required Cpu that});

  BigInt crateApiCpuCpuAutoAccessorGetTotalCpuSpeed({required Cpu that});

  double crateApiCpuCpuAutoAccessorGetTotalCpuUsage({required Cpu that});

  void crateApiCpuCpuAutoAccessorSetAesSupport({
    required Cpu that,
    required bool aesSupport,
  });

  void crateApiCpuCpuAutoAccessorSetCoreSpeeds({
    required Cpu that,
    required Uint64List coreSpeeds,
  });

  void crateApiCpuCpuAutoAccessorSetCoreUsages({
    required Cpu that,
    required Float32List coreUsages,
  });

  void crateApiCpuCpuAutoAccessorSetCpuBrand({
    required Cpu that,
    required String cpuBrand,
  });

  void crateApiCpuCpuAutoAccessorSetCpuCores({
    required Cpu that,
    required BigInt cpuCores,
  });

  void crateApiCpuCpuAutoAccessorSetCpuThreads({
    required Cpu that,
    required BigInt cpuThreads,
  });

  void crateApiCpuCpuAutoAccessorSetCpuVendor({
    required Cpu that,
    required String cpuVendor,
  });

  void crateApiCpuCpuAutoAccessorSetL1Cache({
    required Cpu that,
    required BigInt l1Cache,
  });

  void crateApiCpuCpuAutoAccessorSetL2Cache({
    required Cpu that,
    required BigInt l2Cache,
  });

  void crateApiCpuCpuAutoAccessorSetL3Cache({
    required Cpu that,
    required BigInt l3Cache,
  });

  void crateApiCpuCpuAutoAccessorSetSha256Support({
    required Cpu that,
    required bool sha256Support,
  });

  void crateApiCpuCpuAutoAccessorSetSseFeatures({
    required Cpu that,
    required String sseFeatures,
  });

  void crateApiCpuCpuAutoAccessorSetTotalCpuSpeed({
    required Cpu that,
    required BigInt totalCpuSpeed,
  });

  void crateApiCpuCpuAutoAccessorSetTotalCpuUsage({
    required Cpu that,
    required double totalCpuUsage,
  });

  Future<void> crateApiCpuCpuFetchData({required Cpu that});

  Future<Cpu> crateApiCpuCpuNew();

  Future<List<Process>> crateApiProcessProcessesGetAllProcesses({
    required Processes that,
  });

  Future<void> crateApiProcessProcessesKillProcess({
    required Processes that,
    required int pid,
  });

  Future<Processes> crateApiProcessProcessesNew();

  BigInt crateApiRamRamAutoAccessorGetAvailableRam({required Ram that});

  BigInt crateApiRamRamAutoAccessorGetFreeRam({required Ram that});

  BigInt crateApiRamRamAutoAccessorGetFreeSwap({required Ram that});

  Uint64List crateApiRamRamAutoAccessorGetRamBandWidth({required Ram that});

  Uint64List crateApiRamRamAutoAccessorGetRamSpeed({required Ram that});

  Uint64List crateApiRamRamAutoAccessorGetRamSpeedConfigured({
    required Ram that,
  });

  List<String> crateApiRamRamAutoAccessorGetRamType({required Ram that});

  BigInt crateApiRamRamAutoAccessorGetTotalRam({required Ram that});

  BigInt crateApiRamRamAutoAccessorGetTotalSwap({required Ram that});

  BigInt crateApiRamRamAutoAccessorGetUsedRam({required Ram that});

  BigInt crateApiRamRamAutoAccessorGetUsedSwap({required Ram that});

  void crateApiRamRamAutoAccessorSetAvailableRam({
    required Ram that,
    required BigInt availableRam,
  });

  void crateApiRamRamAutoAccessorSetFreeRam({
    required Ram that,
    required BigInt freeRam,
  });

  void crateApiRamRamAutoAccessorSetFreeSwap({
    required Ram that,
    required BigInt freeSwap,
  });

  void crateApiRamRamAutoAccessorSetRamBandWidth({
    required Ram that,
    required Uint64List ramBandWidth,
  });

  void crateApiRamRamAutoAccessorSetRamSpeed({
    required Ram that,
    required Uint64List ramSpeed,
  });

  void crateApiRamRamAutoAccessorSetRamSpeedConfigured({
    required Ram that,
    required Uint64List ramSpeedConfigured,
  });

  void crateApiRamRamAutoAccessorSetRamType({
    required Ram that,
    required List<String> ramType,
  });

  void crateApiRamRamAutoAccessorSetTotalRam({
    required Ram that,
    required BigInt totalRam,
  });

  void crateApiRamRamAutoAccessorSetTotalSwap({
    required Ram that,
    required BigInt totalSwap,
  });

  void crateApiRamRamAutoAccessorSetUsedRam({
    required Ram that,
    required BigInt usedRam,
  });

  void crateApiRamRamAutoAccessorSetUsedSwap({
    required Ram that,
    required BigInt usedSwap,
  });

  Future<void> crateApiRamRamFetchData({required Ram that});

  Future<Ram> crateApiRamRamNew();

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Cpu;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Cpu;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_CpuPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Processes;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Processes;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ProcessesPtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Ram;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Ram;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RamPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  bool crateApiCpuCpuAutoAccessorGetAesSupport({required Cpu that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorGetAesSupportConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorGetAesSupportConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_get_aes_support",
        argNames: ["that"],
      );

  @override
  Uint64List crateApiCpuCpuAutoAccessorGetCoreSpeeds({required Cpu that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_64_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorGetCoreSpeedsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorGetCoreSpeedsConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_get_core_speeds",
        argNames: ["that"],
      );

  @override
  Float32List crateApiCpuCpuAutoAccessorGetCoreUsages({required Cpu that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorGetCoreUsagesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorGetCoreUsagesConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_get_core_usages",
        argNames: ["that"],
      );

  @override
  String crateApiCpuCpuAutoAccessorGetCpuBrand({required Cpu that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorGetCpuBrandConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorGetCpuBrandConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_get_cpu_brand",
        argNames: ["that"],
      );

  @override
  BigInt crateApiCpuCpuAutoAccessorGetCpuCores({required Cpu that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorGetCpuCoresConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorGetCpuCoresConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_get_cpu_cores",
        argNames: ["that"],
      );

  @override
  BigInt crateApiCpuCpuAutoAccessorGetCpuThreads({required Cpu that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorGetCpuThreadsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorGetCpuThreadsConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_get_cpu_threads",
        argNames: ["that"],
      );

  @override
  String crateApiCpuCpuAutoAccessorGetCpuVendor({required Cpu that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorGetCpuVendorConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorGetCpuVendorConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_get_cpu_vendor",
        argNames: ["that"],
      );

  @override
  BigInt crateApiCpuCpuAutoAccessorGetL1Cache({required Cpu that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorGetL1CacheConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorGetL1CacheConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_get_l1_cache",
        argNames: ["that"],
      );

  @override
  BigInt crateApiCpuCpuAutoAccessorGetL2Cache({required Cpu that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorGetL2CacheConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorGetL2CacheConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_get_l2_cache",
        argNames: ["that"],
      );

  @override
  BigInt crateApiCpuCpuAutoAccessorGetL3Cache({required Cpu that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorGetL3CacheConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorGetL3CacheConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_get_l3_cache",
        argNames: ["that"],
      );

  @override
  bool crateApiCpuCpuAutoAccessorGetSha256Support({required Cpu that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorGetSha256SupportConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorGetSha256SupportConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_get_sha256_support",
        argNames: ["that"],
      );

  @override
  String crateApiCpuCpuAutoAccessorGetSseFeatures({required Cpu that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorGetSseFeaturesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorGetSseFeaturesConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_get_sse_features",
        argNames: ["that"],
      );

  @override
  BigInt crateApiCpuCpuAutoAccessorGetTotalCpuSpeed({required Cpu that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorGetTotalCpuSpeedConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorGetTotalCpuSpeedConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_get_total_cpu_speed",
        argNames: ["that"],
      );

  @override
  double crateApiCpuCpuAutoAccessorGetTotalCpuUsage({required Cpu that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorGetTotalCpuUsageConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorGetTotalCpuUsageConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_get_total_cpu_usage",
        argNames: ["that"],
      );

  @override
  void crateApiCpuCpuAutoAccessorSetAesSupport({
    required Cpu that,
    required bool aesSupport,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          sse_encode_bool(aesSupport, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorSetAesSupportConstMeta,
        argValues: [that, aesSupport],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorSetAesSupportConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_set_aes_support",
        argNames: ["that", "aesSupport"],
      );

  @override
  void crateApiCpuCpuAutoAccessorSetCoreSpeeds({
    required Cpu that,
    required Uint64List coreSpeeds,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          sse_encode_list_prim_u_64_strict(coreSpeeds, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorSetCoreSpeedsConstMeta,
        argValues: [that, coreSpeeds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorSetCoreSpeedsConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_set_core_speeds",
        argNames: ["that", "coreSpeeds"],
      );

  @override
  void crateApiCpuCpuAutoAccessorSetCoreUsages({
    required Cpu that,
    required Float32List coreUsages,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          sse_encode_list_prim_f_32_strict(coreUsages, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorSetCoreUsagesConstMeta,
        argValues: [that, coreUsages],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorSetCoreUsagesConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_set_core_usages",
        argNames: ["that", "coreUsages"],
      );

  @override
  void crateApiCpuCpuAutoAccessorSetCpuBrand({
    required Cpu that,
    required String cpuBrand,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          sse_encode_String(cpuBrand, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorSetCpuBrandConstMeta,
        argValues: [that, cpuBrand],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorSetCpuBrandConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_set_cpu_brand",
        argNames: ["that", "cpuBrand"],
      );

  @override
  void crateApiCpuCpuAutoAccessorSetCpuCores({
    required Cpu that,
    required BigInt cpuCores,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          sse_encode_usize(cpuCores, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorSetCpuCoresConstMeta,
        argValues: [that, cpuCores],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorSetCpuCoresConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_set_cpu_cores",
        argNames: ["that", "cpuCores"],
      );

  @override
  void crateApiCpuCpuAutoAccessorSetCpuThreads({
    required Cpu that,
    required BigInt cpuThreads,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          sse_encode_usize(cpuThreads, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorSetCpuThreadsConstMeta,
        argValues: [that, cpuThreads],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorSetCpuThreadsConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_set_cpu_threads",
        argNames: ["that", "cpuThreads"],
      );

  @override
  void crateApiCpuCpuAutoAccessorSetCpuVendor({
    required Cpu that,
    required String cpuVendor,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          sse_encode_String(cpuVendor, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorSetCpuVendorConstMeta,
        argValues: [that, cpuVendor],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorSetCpuVendorConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_set_cpu_vendor",
        argNames: ["that", "cpuVendor"],
      );

  @override
  void crateApiCpuCpuAutoAccessorSetL1Cache({
    required Cpu that,
    required BigInt l1Cache,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          sse_encode_u_64(l1Cache, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorSetL1CacheConstMeta,
        argValues: [that, l1Cache],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorSetL1CacheConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_set_l1_cache",
        argNames: ["that", "l1Cache"],
      );

  @override
  void crateApiCpuCpuAutoAccessorSetL2Cache({
    required Cpu that,
    required BigInt l2Cache,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          sse_encode_u_64(l2Cache, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorSetL2CacheConstMeta,
        argValues: [that, l2Cache],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorSetL2CacheConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_set_l2_cache",
        argNames: ["that", "l2Cache"],
      );

  @override
  void crateApiCpuCpuAutoAccessorSetL3Cache({
    required Cpu that,
    required BigInt l3Cache,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          sse_encode_u_64(l3Cache, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorSetL3CacheConstMeta,
        argValues: [that, l3Cache],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorSetL3CacheConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_set_l3_cache",
        argNames: ["that", "l3Cache"],
      );

  @override
  void crateApiCpuCpuAutoAccessorSetSha256Support({
    required Cpu that,
    required bool sha256Support,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          sse_encode_bool(sha256Support, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorSetSha256SupportConstMeta,
        argValues: [that, sha256Support],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorSetSha256SupportConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_set_sha256_support",
        argNames: ["that", "sha256Support"],
      );

  @override
  void crateApiCpuCpuAutoAccessorSetSseFeatures({
    required Cpu that,
    required String sseFeatures,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          sse_encode_String(sseFeatures, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorSetSseFeaturesConstMeta,
        argValues: [that, sseFeatures],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorSetSseFeaturesConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_set_sse_features",
        argNames: ["that", "sseFeatures"],
      );

  @override
  void crateApiCpuCpuAutoAccessorSetTotalCpuSpeed({
    required Cpu that,
    required BigInt totalCpuSpeed,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          sse_encode_u_64(totalCpuSpeed, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorSetTotalCpuSpeedConstMeta,
        argValues: [that, totalCpuSpeed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorSetTotalCpuSpeedConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_set_total_cpu_speed",
        argNames: ["that", "totalCpuSpeed"],
      );

  @override
  void crateApiCpuCpuAutoAccessorSetTotalCpuUsage({
    required Cpu that,
    required double totalCpuUsage,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          sse_encode_f_32(totalCpuUsage, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuAutoAccessorSetTotalCpuUsageConstMeta,
        argValues: [that, totalCpuUsage],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuAutoAccessorSetTotalCpuUsageConstMeta =>
      const TaskConstMeta(
        debugName: "Cpu_auto_accessor_set_total_cpu_usage",
        argNames: ["that", "totalCpuUsage"],
      );

  @override
  Future<void> crateApiCpuCpuFetchData({required Cpu that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuFetchDataConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuFetchDataConstMeta =>
      const TaskConstMeta(debugName: "Cpu_fetch_data", argNames: ["that"]);

  @override
  Future<Cpu> crateApiCpuCpuNew() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCpuCpuNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCpuCpuNewConstMeta =>
      const TaskConstMeta(debugName: "Cpu_new", argNames: []);

  @override
  Future<List<Process>> crateApiProcessProcessesGetAllProcesses({
    required Processes that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProcesses(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_process,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProcessProcessesGetAllProcessesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProcessProcessesGetAllProcessesConstMeta =>
      const TaskConstMeta(
        debugName: "Processes_get_all_processes",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiProcessProcessesKillProcess({
    required Processes that,
    required int pid,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProcesses(
            that,
            serializer,
          );
          sse_encode_u_32(pid, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProcessProcessesKillProcessConstMeta,
        argValues: [that, pid],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProcessProcessesKillProcessConstMeta =>
      const TaskConstMeta(
        debugName: "Processes_kill_process",
        argNames: ["that", "pid"],
      );

  @override
  Future<Processes> crateApiProcessProcessesNew() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProcesses,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProcessProcessesNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProcessProcessesNewConstMeta =>
      const TaskConstMeta(debugName: "Processes_new", argNames: []);

  @override
  BigInt crateApiRamRamAutoAccessorGetAvailableRam({required Ram that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 34)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRamRamAutoAccessorGetAvailableRamConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRamRamAutoAccessorGetAvailableRamConstMeta =>
      const TaskConstMeta(
        debugName: "Ram_auto_accessor_get_available_ram",
        argNames: ["that"],
      );

  @override
  BigInt crateApiRamRamAutoAccessorGetFreeRam({required Ram that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 35)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRamRamAutoAccessorGetFreeRamConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRamRamAutoAccessorGetFreeRamConstMeta =>
      const TaskConstMeta(
        debugName: "Ram_auto_accessor_get_free_ram",
        argNames: ["that"],
      );

  @override
  BigInt crateApiRamRamAutoAccessorGetFreeSwap({required Ram that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 36)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRamRamAutoAccessorGetFreeSwapConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRamRamAutoAccessorGetFreeSwapConstMeta =>
      const TaskConstMeta(
        debugName: "Ram_auto_accessor_get_free_swap",
        argNames: ["that"],
      );

  @override
  Uint64List crateApiRamRamAutoAccessorGetRamBandWidth({required Ram that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 37)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_64_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRamRamAutoAccessorGetRamBandWidthConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRamRamAutoAccessorGetRamBandWidthConstMeta =>
      const TaskConstMeta(
        debugName: "Ram_auto_accessor_get_ram_band_width",
        argNames: ["that"],
      );

  @override
  Uint64List crateApiRamRamAutoAccessorGetRamSpeed({required Ram that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 38)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_64_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRamRamAutoAccessorGetRamSpeedConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRamRamAutoAccessorGetRamSpeedConstMeta =>
      const TaskConstMeta(
        debugName: "Ram_auto_accessor_get_ram_speed",
        argNames: ["that"],
      );

  @override
  Uint64List crateApiRamRamAutoAccessorGetRamSpeedConfigured({
    required Ram that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 39)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_64_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRamRamAutoAccessorGetRamSpeedConfiguredConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRamRamAutoAccessorGetRamSpeedConfiguredConstMeta =>
      const TaskConstMeta(
        debugName: "Ram_auto_accessor_get_ram_speed_configured",
        argNames: ["that"],
      );

  @override
  List<String> crateApiRamRamAutoAccessorGetRamType({required Ram that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 40)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRamRamAutoAccessorGetRamTypeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRamRamAutoAccessorGetRamTypeConstMeta =>
      const TaskConstMeta(
        debugName: "Ram_auto_accessor_get_ram_type",
        argNames: ["that"],
      );

  @override
  BigInt crateApiRamRamAutoAccessorGetTotalRam({required Ram that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 41)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRamRamAutoAccessorGetTotalRamConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRamRamAutoAccessorGetTotalRamConstMeta =>
      const TaskConstMeta(
        debugName: "Ram_auto_accessor_get_total_ram",
        argNames: ["that"],
      );

  @override
  BigInt crateApiRamRamAutoAccessorGetTotalSwap({required Ram that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 42)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRamRamAutoAccessorGetTotalSwapConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRamRamAutoAccessorGetTotalSwapConstMeta =>
      const TaskConstMeta(
        debugName: "Ram_auto_accessor_get_total_swap",
        argNames: ["that"],
      );

  @override
  BigInt crateApiRamRamAutoAccessorGetUsedRam({required Ram that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 43)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRamRamAutoAccessorGetUsedRamConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRamRamAutoAccessorGetUsedRamConstMeta =>
      const TaskConstMeta(
        debugName: "Ram_auto_accessor_get_used_ram",
        argNames: ["that"],
      );

  @override
  BigInt crateApiRamRamAutoAccessorGetUsedSwap({required Ram that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 44)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRamRamAutoAccessorGetUsedSwapConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRamRamAutoAccessorGetUsedSwapConstMeta =>
      const TaskConstMeta(
        debugName: "Ram_auto_accessor_get_used_swap",
        argNames: ["that"],
      );

  @override
  void crateApiRamRamAutoAccessorSetAvailableRam({
    required Ram that,
    required BigInt availableRam,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
            that,
            serializer,
          );
          sse_encode_u_64(availableRam, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 45)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRamRamAutoAccessorSetAvailableRamConstMeta,
        argValues: [that, availableRam],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRamRamAutoAccessorSetAvailableRamConstMeta =>
      const TaskConstMeta(
        debugName: "Ram_auto_accessor_set_available_ram",
        argNames: ["that", "availableRam"],
      );

  @override
  void crateApiRamRamAutoAccessorSetFreeRam({
    required Ram that,
    required BigInt freeRam,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
            that,
            serializer,
          );
          sse_encode_u_64(freeRam, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 46)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRamRamAutoAccessorSetFreeRamConstMeta,
        argValues: [that, freeRam],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRamRamAutoAccessorSetFreeRamConstMeta =>
      const TaskConstMeta(
        debugName: "Ram_auto_accessor_set_free_ram",
        argNames: ["that", "freeRam"],
      );

  @override
  void crateApiRamRamAutoAccessorSetFreeSwap({
    required Ram that,
    required BigInt freeSwap,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
            that,
            serializer,
          );
          sse_encode_u_64(freeSwap, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 47)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRamRamAutoAccessorSetFreeSwapConstMeta,
        argValues: [that, freeSwap],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRamRamAutoAccessorSetFreeSwapConstMeta =>
      const TaskConstMeta(
        debugName: "Ram_auto_accessor_set_free_swap",
        argNames: ["that", "freeSwap"],
      );

  @override
  void crateApiRamRamAutoAccessorSetRamBandWidth({
    required Ram that,
    required Uint64List ramBandWidth,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
            that,
            serializer,
          );
          sse_encode_list_prim_u_64_strict(ramBandWidth, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 48)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRamRamAutoAccessorSetRamBandWidthConstMeta,
        argValues: [that, ramBandWidth],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRamRamAutoAccessorSetRamBandWidthConstMeta =>
      const TaskConstMeta(
        debugName: "Ram_auto_accessor_set_ram_band_width",
        argNames: ["that", "ramBandWidth"],
      );

  @override
  void crateApiRamRamAutoAccessorSetRamSpeed({
    required Ram that,
    required Uint64List ramSpeed,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
            that,
            serializer,
          );
          sse_encode_list_prim_u_64_strict(ramSpeed, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 49)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRamRamAutoAccessorSetRamSpeedConstMeta,
        argValues: [that, ramSpeed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRamRamAutoAccessorSetRamSpeedConstMeta =>
      const TaskConstMeta(
        debugName: "Ram_auto_accessor_set_ram_speed",
        argNames: ["that", "ramSpeed"],
      );

  @override
  void crateApiRamRamAutoAccessorSetRamSpeedConfigured({
    required Ram that,
    required Uint64List ramSpeedConfigured,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
            that,
            serializer,
          );
          sse_encode_list_prim_u_64_strict(ramSpeedConfigured, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 50)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRamRamAutoAccessorSetRamSpeedConfiguredConstMeta,
        argValues: [that, ramSpeedConfigured],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRamRamAutoAccessorSetRamSpeedConfiguredConstMeta =>
      const TaskConstMeta(
        debugName: "Ram_auto_accessor_set_ram_speed_configured",
        argNames: ["that", "ramSpeedConfigured"],
      );

  @override
  void crateApiRamRamAutoAccessorSetRamType({
    required Ram that,
    required List<String> ramType,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
            that,
            serializer,
          );
          sse_encode_list_String(ramType, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 51)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRamRamAutoAccessorSetRamTypeConstMeta,
        argValues: [that, ramType],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRamRamAutoAccessorSetRamTypeConstMeta =>
      const TaskConstMeta(
        debugName: "Ram_auto_accessor_set_ram_type",
        argNames: ["that", "ramType"],
      );

  @override
  void crateApiRamRamAutoAccessorSetTotalRam({
    required Ram that,
    required BigInt totalRam,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
            that,
            serializer,
          );
          sse_encode_u_64(totalRam, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 52)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRamRamAutoAccessorSetTotalRamConstMeta,
        argValues: [that, totalRam],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRamRamAutoAccessorSetTotalRamConstMeta =>
      const TaskConstMeta(
        debugName: "Ram_auto_accessor_set_total_ram",
        argNames: ["that", "totalRam"],
      );

  @override
  void crateApiRamRamAutoAccessorSetTotalSwap({
    required Ram that,
    required BigInt totalSwap,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
            that,
            serializer,
          );
          sse_encode_u_64(totalSwap, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 53)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRamRamAutoAccessorSetTotalSwapConstMeta,
        argValues: [that, totalSwap],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRamRamAutoAccessorSetTotalSwapConstMeta =>
      const TaskConstMeta(
        debugName: "Ram_auto_accessor_set_total_swap",
        argNames: ["that", "totalSwap"],
      );

  @override
  void crateApiRamRamAutoAccessorSetUsedRam({
    required Ram that,
    required BigInt usedRam,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
            that,
            serializer,
          );
          sse_encode_u_64(usedRam, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 54)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRamRamAutoAccessorSetUsedRamConstMeta,
        argValues: [that, usedRam],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRamRamAutoAccessorSetUsedRamConstMeta =>
      const TaskConstMeta(
        debugName: "Ram_auto_accessor_set_used_ram",
        argNames: ["that", "usedRam"],
      );

  @override
  void crateApiRamRamAutoAccessorSetUsedSwap({
    required Ram that,
    required BigInt usedSwap,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
            that,
            serializer,
          );
          sse_encode_u_64(usedSwap, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 55)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRamRamAutoAccessorSetUsedSwapConstMeta,
        argValues: [that, usedSwap],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRamRamAutoAccessorSetUsedSwapConstMeta =>
      const TaskConstMeta(
        debugName: "Ram_auto_accessor_set_used_swap",
        argNames: ["that", "usedSwap"],
      );

  @override
  Future<void> crateApiRamRamFetchData({required Ram that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 56,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRamRamFetchDataConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRamRamFetchDataConstMeta =>
      const TaskConstMeta(debugName: "Ram_fetch_data", argNames: ["that"]);

  @override
  Future<Ram> crateApiRamRamNew() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 57,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRamRamNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRamRamNewConstMeta =>
      const TaskConstMeta(debugName: "Ram_new", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Cpu => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Cpu => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Processes => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProcesses;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Processes => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProcesses;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Ram => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Ram => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam;

  @protected
  Cpu
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CpuImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Processes
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProcesses(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ProcessesImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Ram
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RamImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Cpu
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CpuImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Processes
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProcesses(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ProcessesImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Ram
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RamImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Cpu
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CpuImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Ram
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RamImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Cpu
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CpuImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Processes
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProcesses(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ProcessesImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Ram
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RamImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeUint64List(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Process> dco_decode_list_process(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_process).toList();
  }

  @protected
  Process dco_decode_process(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Process(
      name: dco_decode_String(arr[0]),
      usage: dco_decode_f_32(arr[1]),
      pid: dco_decode_u_32(arr[2]),
      memory: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  Cpu
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CpuImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Processes
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProcesses(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ProcessesImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Ram
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RamImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Cpu
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CpuImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Processes
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProcesses(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ProcessesImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Ram
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RamImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Cpu
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CpuImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Ram
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RamImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Cpu
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CpuImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Processes
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProcesses(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ProcessesImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Ram
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RamImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Process> sse_decode_list_process(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Process>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_process(deserializer));
    }
    return ans_;
  }

  @protected
  Process sse_decode_process(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_usage = sse_decode_f_32(deserializer);
    var var_pid = sse_decode_u_32(deserializer);
    var var_memory = sse_decode_u_64(deserializer);
    return Process(
      name: var_name,
      usage: var_usage,
      pid: var_pid,
      memory: var_memory,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
    Cpu self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CpuImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProcesses(
    Processes self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ProcessesImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
    Ram self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RamImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
    Cpu self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CpuImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProcesses(
    Processes self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ProcessesImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
    Ram self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RamImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
    Cpu self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CpuImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
    Ram self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RamImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCpu(
    Cpu self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CpuImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProcesses(
    Processes self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ProcessesImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRam(
    Ram self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RamImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_64_strict(
    Uint64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_process(List<Process> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_process(item, serializer);
    }
  }

  @protected
  void sse_encode_process(Process self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_f_32(self.usage, serializer);
    sse_encode_u_32(self.pid, serializer);
    sse_encode_u_64(self.memory, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class CpuImpl extends RustOpaque implements Cpu {
  // Not to be used by end users
  CpuImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CpuImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Cpu,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Cpu,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_CpuPtr,
  );

  bool get aesSupport =>
      RustLib.instance.api.crateApiCpuCpuAutoAccessorGetAesSupport(that: this);

  Uint64List get coreSpeeds =>
      RustLib.instance.api.crateApiCpuCpuAutoAccessorGetCoreSpeeds(that: this);

  Float32List get coreUsages =>
      RustLib.instance.api.crateApiCpuCpuAutoAccessorGetCoreUsages(that: this);

  String get cpuBrand =>
      RustLib.instance.api.crateApiCpuCpuAutoAccessorGetCpuBrand(that: this);

  BigInt get cpuCores =>
      RustLib.instance.api.crateApiCpuCpuAutoAccessorGetCpuCores(that: this);

  BigInt get cpuThreads =>
      RustLib.instance.api.crateApiCpuCpuAutoAccessorGetCpuThreads(that: this);

  String get cpuVendor =>
      RustLib.instance.api.crateApiCpuCpuAutoAccessorGetCpuVendor(that: this);

  BigInt get l1Cache =>
      RustLib.instance.api.crateApiCpuCpuAutoAccessorGetL1Cache(that: this);

  BigInt get l2Cache =>
      RustLib.instance.api.crateApiCpuCpuAutoAccessorGetL2Cache(that: this);

  BigInt get l3Cache =>
      RustLib.instance.api.crateApiCpuCpuAutoAccessorGetL3Cache(that: this);

  bool get sha256Support => RustLib.instance.api
      .crateApiCpuCpuAutoAccessorGetSha256Support(that: this);

  String get sseFeatures =>
      RustLib.instance.api.crateApiCpuCpuAutoAccessorGetSseFeatures(that: this);

  BigInt get totalCpuSpeed => RustLib.instance.api
      .crateApiCpuCpuAutoAccessorGetTotalCpuSpeed(that: this);

  double get totalCpuUsage => RustLib.instance.api
      .crateApiCpuCpuAutoAccessorGetTotalCpuUsage(that: this);

  set aesSupport(bool aesSupport) =>
      RustLib.instance.api.crateApiCpuCpuAutoAccessorSetAesSupport(
        that: this,
        aesSupport: aesSupport,
      );

  set coreSpeeds(Uint64List coreSpeeds) =>
      RustLib.instance.api.crateApiCpuCpuAutoAccessorSetCoreSpeeds(
        that: this,
        coreSpeeds: coreSpeeds,
      );

  set coreUsages(Float32List coreUsages) =>
      RustLib.instance.api.crateApiCpuCpuAutoAccessorSetCoreUsages(
        that: this,
        coreUsages: coreUsages,
      );

  set cpuBrand(String cpuBrand) => RustLib.instance.api
      .crateApiCpuCpuAutoAccessorSetCpuBrand(that: this, cpuBrand: cpuBrand);

  set cpuCores(BigInt cpuCores) => RustLib.instance.api
      .crateApiCpuCpuAutoAccessorSetCpuCores(that: this, cpuCores: cpuCores);

  set cpuThreads(BigInt cpuThreads) =>
      RustLib.instance.api.crateApiCpuCpuAutoAccessorSetCpuThreads(
        that: this,
        cpuThreads: cpuThreads,
      );

  set cpuVendor(String cpuVendor) => RustLib.instance.api
      .crateApiCpuCpuAutoAccessorSetCpuVendor(that: this, cpuVendor: cpuVendor);

  set l1Cache(BigInt l1Cache) => RustLib.instance.api
      .crateApiCpuCpuAutoAccessorSetL1Cache(that: this, l1Cache: l1Cache);

  set l2Cache(BigInt l2Cache) => RustLib.instance.api
      .crateApiCpuCpuAutoAccessorSetL2Cache(that: this, l2Cache: l2Cache);

  set l3Cache(BigInt l3Cache) => RustLib.instance.api
      .crateApiCpuCpuAutoAccessorSetL3Cache(that: this, l3Cache: l3Cache);

  set sha256Support(bool sha256Support) =>
      RustLib.instance.api.crateApiCpuCpuAutoAccessorSetSha256Support(
        that: this,
        sha256Support: sha256Support,
      );

  set sseFeatures(String sseFeatures) =>
      RustLib.instance.api.crateApiCpuCpuAutoAccessorSetSseFeatures(
        that: this,
        sseFeatures: sseFeatures,
      );

  set totalCpuSpeed(BigInt totalCpuSpeed) =>
      RustLib.instance.api.crateApiCpuCpuAutoAccessorSetTotalCpuSpeed(
        that: this,
        totalCpuSpeed: totalCpuSpeed,
      );

  set totalCpuUsage(double totalCpuUsage) =>
      RustLib.instance.api.crateApiCpuCpuAutoAccessorSetTotalCpuUsage(
        that: this,
        totalCpuUsage: totalCpuUsage,
      );

  Future<void> fetchData() =>
      RustLib.instance.api.crateApiCpuCpuFetchData(that: this);
}

@sealed
class ProcessesImpl extends RustOpaque implements Processes {
  // Not to be used by end users
  ProcessesImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ProcessesImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Processes,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Processes,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ProcessesPtr,
  );

  Future<List<Process>> getAllProcesses() =>
      RustLib.instance.api.crateApiProcessProcessesGetAllProcesses(that: this);

  Future<void> killProcess({required int pid}) => RustLib.instance.api
      .crateApiProcessProcessesKillProcess(that: this, pid: pid);
}

@sealed
class RamImpl extends RustOpaque implements Ram {
  // Not to be used by end users
  RamImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  RamImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Ram,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Ram,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_RamPtr,
  );

  BigInt get availableRam => RustLib.instance.api
      .crateApiRamRamAutoAccessorGetAvailableRam(that: this);

  BigInt get freeRam =>
      RustLib.instance.api.crateApiRamRamAutoAccessorGetFreeRam(that: this);

  BigInt get freeSwap =>
      RustLib.instance.api.crateApiRamRamAutoAccessorGetFreeSwap(that: this);

  Uint64List get ramBandWidth => RustLib.instance.api
      .crateApiRamRamAutoAccessorGetRamBandWidth(that: this);

  Uint64List get ramSpeed =>
      RustLib.instance.api.crateApiRamRamAutoAccessorGetRamSpeed(that: this);

  Uint64List get ramSpeedConfigured => RustLib.instance.api
      .crateApiRamRamAutoAccessorGetRamSpeedConfigured(that: this);

  List<String> get ramType =>
      RustLib.instance.api.crateApiRamRamAutoAccessorGetRamType(that: this);

  BigInt get totalRam =>
      RustLib.instance.api.crateApiRamRamAutoAccessorGetTotalRam(that: this);

  BigInt get totalSwap =>
      RustLib.instance.api.crateApiRamRamAutoAccessorGetTotalSwap(that: this);

  BigInt get usedRam =>
      RustLib.instance.api.crateApiRamRamAutoAccessorGetUsedRam(that: this);

  BigInt get usedSwap =>
      RustLib.instance.api.crateApiRamRamAutoAccessorGetUsedSwap(that: this);

  set availableRam(BigInt availableRam) =>
      RustLib.instance.api.crateApiRamRamAutoAccessorSetAvailableRam(
        that: this,
        availableRam: availableRam,
      );

  set freeRam(BigInt freeRam) => RustLib.instance.api
      .crateApiRamRamAutoAccessorSetFreeRam(that: this, freeRam: freeRam);

  set freeSwap(BigInt freeSwap) => RustLib.instance.api
      .crateApiRamRamAutoAccessorSetFreeSwap(that: this, freeSwap: freeSwap);

  set ramBandWidth(Uint64List ramBandWidth) =>
      RustLib.instance.api.crateApiRamRamAutoAccessorSetRamBandWidth(
        that: this,
        ramBandWidth: ramBandWidth,
      );

  set ramSpeed(Uint64List ramSpeed) => RustLib.instance.api
      .crateApiRamRamAutoAccessorSetRamSpeed(that: this, ramSpeed: ramSpeed);

  set ramSpeedConfigured(Uint64List ramSpeedConfigured) =>
      RustLib.instance.api.crateApiRamRamAutoAccessorSetRamSpeedConfigured(
        that: this,
        ramSpeedConfigured: ramSpeedConfigured,
      );

  set ramType(List<String> ramType) => RustLib.instance.api
      .crateApiRamRamAutoAccessorSetRamType(that: this, ramType: ramType);

  set totalRam(BigInt totalRam) => RustLib.instance.api
      .crateApiRamRamAutoAccessorSetTotalRam(that: this, totalRam: totalRam);

  set totalSwap(BigInt totalSwap) => RustLib.instance.api
      .crateApiRamRamAutoAccessorSetTotalSwap(that: this, totalSwap: totalSwap);

  set usedRam(BigInt usedRam) => RustLib.instance.api
      .crateApiRamRamAutoAccessorSetUsedRam(that: this, usedRam: usedRam);

  set usedSwap(BigInt usedSwap) => RustLib.instance.api
      .crateApiRamRamAutoAccessorSetUsedSwap(that: this, usedSwap: usedSwap);

  Future<void> fetchData() =>
      RustLib.instance.api.crateApiRamRamFetchData(that: this);
}
