// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_cpu_speed`

Future<Float32List> getCoreUsages() =>
    RustLib.instance.api.crateApiCpuGetCoreUsages();

Future<Uint64List> getCpusSpeed() =>
    RustLib.instance.api.crateApiCpuGetCpusSpeed();

Future<String> getVendor() => RustLib.instance.api.crateApiCpuGetVendor();

Future<String> getBrand() => RustLib.instance.api.crateApiCpuGetBrand();

Future<BigInt> getPhysicalCores() =>
    RustLib.instance.api.crateApiCpuGetPhysicalCores();

Future<BigInt> getThreads() => RustLib.instance.api.crateApiCpuGetThreads();

Future<(BigInt, BigInt)> getL1Cache() =>
    RustLib.instance.api.crateApiCpuGetL1Cache();

Future<BigInt> getL2Cache() => RustLib.instance.api.crateApiCpuGetL2Cache();

Future<(BigInt, BigInt)> getL3Cache() =>
    RustLib.instance.api.crateApiCpuGetL3Cache();

Future<bool> getHashAcceleration() =>
    RustLib.instance.api.crateApiCpuGetHashAcceleration();

Future<bool> getEncryptionAcceleration() =>
    RustLib.instance.api.crateApiCpuGetEncryptionAcceleration();

Future<String> getSseExtensions() =>
    RustLib.instance.api.crateApiCpuGetSseExtensions();
