// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_brand`, `get_core_usages`, `get_cores_and_threads`, `get_cpu_speeds`, `get_encryption_acceleration`, `get_hash_acceleration`, `get_l1_cache`, `get_l2_cache`, `get_l3_cache`, `get_sse_extensions`, `get_total_cpu_speed`, `get_total_cpu_usage`, `get_vendor`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Cpu>>
abstract class Cpu implements RustOpaqueInterface {
  bool get aesSupport;

  Uint64List get coreSpeeds;

  Float32List get coreUsages;

  String get cpuBrand;

  BigInt get cpuCores;

  BigInt get cpuThreads;

  String get cpuVendor;

  BigInt get l1Cache;

  BigInt get l2Cache;

  BigInt get l3Cache;

  bool get sha256Support;

  String get sseFeatures;

  BigInt get totalCpuSpeed;

  double get totalCpuUsage;

  set aesSupport(bool aesSupport);

  set coreSpeeds(Uint64List coreSpeeds);

  set coreUsages(Float32List coreUsages);

  set cpuBrand(String cpuBrand);

  set cpuCores(BigInt cpuCores);

  set cpuThreads(BigInt cpuThreads);

  set cpuVendor(String cpuVendor);

  set l1Cache(BigInt l1Cache);

  set l2Cache(BigInt l2Cache);

  set l3Cache(BigInt l3Cache);

  set sha256Support(bool sha256Support);

  set sseFeatures(String sseFeatures);

  set totalCpuSpeed(BigInt totalCpuSpeed);

  set totalCpuUsage(double totalCpuUsage);

  Future<void> fetchData();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Cpu> newInstance() => RustLib.instance.api.crateApiCpuCpuNew();
}
