// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_ram_band_width`, `get_ram_speed_configured`, `get_ram_speed_current`, `get_ram_type`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Ram>>
abstract class Ram implements RustOpaqueInterface {
  BigInt get availableRam;

  BigInt get freeRam;

  BigInt get freeSwap;

  Uint64List get ramBandWidth;

  Uint64List get ramSpeed;

  Uint64List get ramSpeedConfigured;

  List<String> get ramType;

  BigInt get totalRam;

  BigInt get totalSwap;

  BigInt get usedRam;

  BigInt get usedSwap;

  set availableRam(BigInt availableRam);

  set freeRam(BigInt freeRam);

  set freeSwap(BigInt freeSwap);

  set ramBandWidth(Uint64List ramBandWidth);

  set ramSpeed(Uint64List ramSpeed);

  set ramSpeedConfigured(Uint64List ramSpeedConfigured);

  set ramType(List<String> ramType);

  set totalRam(BigInt totalRam);

  set totalSwap(BigInt totalSwap);

  set usedRam(BigInt usedRam);

  set usedSwap(BigInt usedSwap);

  Future<void> fetchData();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Ram> newInstance() => RustLib.instance.api.crateApiRamRamNew();
}
