// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<BigInt> getTotalRam() => RustLib.instance.api.crateApiRamGetTotalRam();

Future<BigInt> getFreeRam() => RustLib.instance.api.crateApiRamGetFreeRam();

Future<BigInt> getAvailableRam() =>
    RustLib.instance.api.crateApiRamGetAvailableRam();

Future<BigInt> getUsedMemory() =>
    RustLib.instance.api.crateApiRamGetUsedMemory();

Future<BigInt> getTotalSwap() => RustLib.instance.api.crateApiRamGetTotalSwap();

Future<BigInt> getFreeSwap() => RustLib.instance.api.crateApiRamGetFreeSwap();

Future<BigInt> getUsedSwap() => RustLib.instance.api.crateApiRamGetUsedSwap();
